// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_goshopping.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhzbd9UeWSuBg8C3MNAsrIWO1gjuZFQM',
    appId: '1:101786579290:web:67893bdb31048352a78363',
    messagingSenderId: '101786579290',
    projectId: 'goshopping-48db9',
    authDomain: 'goshopping-48db9.firebaseapp.com',
    storageBucket: 'goshopping-48db9.firebasestorage.app',
    measurementId: 'G-H3RHPJB3XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOrH6NiWn6nUhpdgnZ328hQ9Yel-ECFf4',
    appId: '1:101786579290:android:ade6ffa07b6aaaeda78363',
    messagingSenderId: '101786579290',
    projectId: 'goshopping-48db9',
    storageBucket: 'goshopping-48db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgauCbShRE1og3U3_a6EQWmycZqgu4y6w',
    appId: '1:101786579290:ios:35f67f6447f85ebba78363',
    messagingSenderId: '101786579290',
    projectId: 'goshopping-48db9',
    storageBucket: 'goshopping-48db9.firebasestorage.app',
    iosBundleId: 'com.oneness-as.goshopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhzbd9UeWSuBg8C3MNAsrIWO1gjuZFQM',
    appId: '1:101786579290:web:a366ef016807703da78363',
    messagingSenderId: '101786579290',
    projectId: 'goshopping-48db9',
    authDomain: 'goshopping-48db9.firebaseapp.com',
    storageBucket: 'goshopping-48db9.firebasestorage.app',
    measurementId: 'G-W6Y6E20LKR',
  );
}
